
import javax.swing.JOptionPane;
import model.User;
import data.UserData;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Samet
 */
public class Signup extends javax.swing.JFrame {
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String telefonNoPattern = "^[0-9]*$";
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        btnKaydet.setEnabled(false);
    }
    public void clear(){
        txtAd.setText("");
        txtEmail.setText("");
        txtTelNo.setText("");
        txtAdres.setText("");
        txtSoru.setText("");
        txtCevap.setText("");
        txtSifre.setText("");
        btnKaydet.setEnabled(false);
        
        
    }
    public void validateFields(){
        String ad = txtAd.getText();
        String email = txtEmail.getText();
        String telNo= txtTelNo.getText();
        String adres = txtAdres.getText();
        String soru = txtSoru.getText();
        String cevap = txtCevap.getText();
        String sifre = txtSifre.getText();
        
        if(!ad.equals("")&& email.matches(emailPattern)&& telNo.matches(telefonNoPattern)&& telNo.length()==10&&!adres.equals("")&&!sifre.equals("")&&!soru.equals("")&&!cevap.equals("")){
            btnKaydet.setEnabled(true);
        }else
            btnKaydet.setEnabled(false);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        txtAd = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        txtSoru = new javax.swing.JTextField();
        txtCevap = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kayıt Ol");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 119, 158, 33));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 75, 26));

        jLabel3.setText("Ad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 169, 75, 26));

        jLabel4.setText("Tel No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 233, 75, 26));

        jLabel5.setText("Şifre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 297, 75, 26));

        jLabel6.setText("Adres");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 265, 75, 26));

        jLabel7.setText("Güvenlik Sorusu");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 329, 94, 26));

        jLabel8.setText("Cevap");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 361, 94, 26));
        getContentPane().add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 250, -1));

        txtAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdKeyReleased(evt);
            }
        });
        getContentPane().add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 171, 246, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 203, 246, -1));

        txtTelNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 235, 246, -1));

        txtAdres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdresKeyReleased(evt);
            }
        });
        getContentPane().add(txtAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 267, 246, -1));

        txtSoru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoruKeyReleased(evt);
            }
        });
        getContentPane().add(txtSoru, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 331, 246, -1));

        txtCevap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCevapKeyReleased(evt);
            }
        });
        getContentPane().add(txtCevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 363, 246, -1));

        btnKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        btnSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnSil.setText("Clear");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });
        getContentPane().add(btnSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, 30));

        btnCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });
        getContentPane().add(btnCikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        jButton4.setText("Parolayı Unuttum");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        jButton5.setText("Giriş");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application","Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        User user = new User();
        user.setIsim(txtAd.getText());
        user.setEmail(txtEmail.getText());
        user.setTelefonNo(txtTelNo.getText());
        user.setAdres(txtAdres.getText());
        user.setSifre(txtSifre.getText());
        user.setSoru(txtSoru.getText());
        user.setCevap(txtCevap.getText());
        UserData.save(user);
        clear();
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        clear();
    }//GEN-LAST:event_btnSilActionPerformed

    private void txtAdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyReleased
        validateFields();
    }//GEN-LAST:event_txtAdKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTelNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNoKeyReleased
        validateFields();
    }//GEN-LAST:event_txtTelNoKeyReleased

    private void txtAdresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdresKeyReleased
        validateFields();
    }//GEN-LAST:event_txtAdresKeyReleased

    private void txtSoruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoruKeyReleased
        validateFields();
    }//GEN-LAST:event_txtSoruKeyReleased

    private void txtCevapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCevapKeyReleased
        validateFields(); 
    }//GEN-LAST:event_txtCevapKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtCevap;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSifre;
    private javax.swing.JTextField txtSoru;
    private javax.swing.JTextField txtTelNo;
    // End of variables declaration//GEN-END:variables
}
